### ISSUE TITLE
PPI recognize postfix dereference tokens incorrectly

### ISSUE THREAD

**Issue by zdm** [adamkennedy/PPI#88] opened 2014-08-23 06:08 UTC
tested with:

```
$sref->$*;
$aref->@*;
$aref->$#*;
$href->%*;
$cref->&*;
$gref->**;
```

**Comment by trwyant** [comment] 2018-06-21 15:43
I am interested in attempting this. My proposed parse is to make them a PPI::Token::Cast. If it's a slice, this would be followed by a PPI::Structure::Subscript. The cast object would contain just the postfix dereference (that is, '$*' and friends), not the right arrow operator.

Comments? Would you prefer another implementation?

**Comment by trwyant** [comment] 2018-06-21 16:33
Looks like this is already in the Git repository. Thank you very much.

**Comment by zdm** [comment] 2018-11-04 19:41
Whether this issue fixed? 
It is still present for me.

**Comment by akiym** [comment] 2018-11-04 20:03
Fixed in version 1.237_001. But it's still dev release.
@wchristian Could you release version 1.238 on CPAN?

**Comment by zdm** [comment] 2019-11-30 20:22
Current PPI version is 1.270, bug is still exists.

**Comment by wchristian** [comment] 2019-12-02 21:17
@zdm These tests pass in all tests i've seen of PPI: https://metacpan.org/source/MITHALDU/PPI-1.270/t/ppi_token_unknown.t#L466-600

Can you please give me code that demonstrates the exact bug you're seeing?

**Comment by zdm** [comment] 2019-12-02 22:00
It is not works for me.
I am using examples from the first message in this issue and get errors.
```
References::ProhibitDoubleSigils - Double-sigil dereference
```
When I disable rule "References::ProhibitDoubleSigils" no errors occurred.

**Comment by wchristian** [comment] 2019-12-03 14:19
@zdm That's not a bug in PPI, that's a bug in that policy which wasn't updated to take into account that Token::Cast can now NOT have a block after it, if it is preceeded by a dereference operator.

Please report this bug in Perl-Critic. :)

**Closed by wchristian** 2019-12-03 14:19 UTC
Labels: bug, misparse
