### ISSUE TITLE
Linux failures on t/08-regression.t because of a trailing ^M in the "expected" string.

### ISSUE THREAD

**Issue by daoswald** [adamkennedy/PPI#243] opened 2019-05-16 02:22 UTC
See the following example:
`$ cat -A .cpanm/work/1557972694.22265/build.log |grep expected -C 5
$
#   Failed test 't/data/08_regression/45_heredoc_w_paren_in_terminator: Generated dump matches stored dump'$
#   at t/lib/PPI/Test/Run.pm line 72.$
#     Structures begin differing at:$
#          $got->[0] = 'PPI::Document'$
#     $expected->[0] = 'PPI::Document^M'$
# PPI::Document$
#   PPI::Statement$
#     PPI::Token::Magic  ^I'_'$
#     PPI::Token::Operator  ^I'+'$
#     PPI::Token::Comment  ^I'#8r\tt`-['$
`

I used cat -A to show special characters. You can see the trailing ^M in $expected.  There are many failures after this point, but that's the first one.

**Comment by GeJ** [comment] 2019-05-16 05:41
Same error on FreeBSD with perl 5.28.2

```perl
t/07_token.t ..................... ok

#   Failed test 't/data/08_regression/45_heredoc_w_paren_in_terminator: Generated dump matches stored dump'
#   at t/lib/PPI/Test/Run.pm line 72.
#     Structures begin differing at:
#          $got->[0] = 'PPI::Document'
#     $expected->[0] = 'PPI::Document^M'
# PPI::Document
#   PPI::Statement
#     PPI::Token::Magic         '_'
#     PPI::Token::Operator      '+'
#     PPI::Token::Comment       '#8r\tt`-['
#     PPI::Token::Whitespace    '\n'
#     PPI::Token::Operator      '<'
#     PPI::Token::Operator      '+'
#     PPI::Token::Number        '0'
#     PPI::Token::Word          'cXV'
#     PPI::Token::Operator      '!='
#     PPI::Token::Operator      '.'
#     PPI::Token::Operator      '?'
#     PPI::Token::Word          'c'
#     PPI::Token::Operator      '!'
#     PPI::Token::Word          'c0'
#     PPI::Token::Operator      '='
#   PPI::Statement::UnmatchedBrace
#     PPI::Token::Structure     ')'
#   PPI::Statement
#     PPI::Token::HereDoc       '<<~')19_-b+?WW''
#     PPI::Structure::Constructor       [ ... ???
#       PPI::Statement
#         PPI::Token::Word      'z'
#         PPI::Token::Whitespace        ' '
#         PPI::Token::Quote::Literal    'q-y?#m@Wt>.'.xg=}|*w|:+[|9}"mW:Xf()?(cx9*<\t\n'

#   Failed test 't/data/08_regression/46_heredoc_w_paren_in_terminator: Generated dump matches stored dump'
#   at t/lib/PPI/Test/Run.pm line 72.
#     Structures begin differing at:
#          $got->[0] = 'PPI::Document'
#     $expected->[0] = 'PPI::Document^M'
# PPI::Document
#   PPI::Statement
#     PPI::Token::HereDoc       '<<~` (y0<"wsxV?[\tV q`'
#     PPI::Token::Operator      '+'
#     PPI::Token::Quote::Double         '"<X)[/b&g+.{\`b/)z]\%=?s@ x,`@1q,^{Vs0)gtm_^0*;>{/*9's,\t!\*"'
#     PPI::Token::Word          'r'
#   PPI::Token::Whitespace      '\n'

#   Failed test 't/data/08_regression/47_heredoc_w_paren_in_terminator: Generated dump matches stored dump'
#   at t/lib/PPI/Test/Run.pm line 72.
#     Structures begin differing at:
#          $got->[0] = 'PPI::Document'
#     $expected->[0] = 'PPI::Document^M'
# PPI::Document
#   PPI::Statement
#     PPI::Token::Operator      '.'
#     PPI::Token::Word          'ty'
#     PPI::Token::Symbol        '*m'
#     PPI::Token::Symbol        '$s_'
#     PPI::Token::Comment       '# w\t\99&#w[>W\!WfV9s?@]m|=#8X<~=st:)/=y'
#     PPI::Token::Whitespace    '\n'
#     PPI::Token::Number        '8'
#     PPI::Token::Operator      '^'
#     PPI::Token::Word          'V'
#     PPI::Token::Cast          '\'
#     PPI::Token::Word          'w'
#     PPI::Token::QuoteLike::Backtick   '`981]]g\tm'q,msx/>@{;^>1.@?>[g-9|%`'
#     PPI::Token::Whitespace    '\t\t'
#     PPI::Token::HereDoc       '<<~'?w` "^(\ty>*bV (smy{"0=s=11@!}<8-]/}%-yX"",!8y''
#     PPI::Token::Word          'z'
#     PPI::Token::Operator      '-'
#   PPI::Token::Comment         '#$<c(@*.[`;"|=;f<(W;]!_^]{g<|8'
#   PPI::Token::Whitespace      '\n'

#   Failed test 't/data/08_regression/48_heredoc_w_paren_in_terminator: Generated dump matches stored dump'
#   at t/lib/PPI/Test/Run.pm line 72.
#     Structures begin differing at:
#          $got->[0] = 'PPI::Document'
#     $expected->[0] = 'PPI::Document^M'
# PPI::Document
#   PPI::Statement::Null
#     PPI::Token::Structure     ';'
#   PPI::Statement::UnmatchedBrace
#     PPI::Token::Structure     ')'
#   PPI::Statement
#     PPI::Token::Operator      '&'
#     PPI::Token::Operator      '>>'
#     PPI::Token::Word          'qbc'
#     PPI::Structure::Block     { ... ???
#       PPI::Statement
#         PPI::Token::Symbol    '$b'
#         PPI::Token::Operator          '|'
#         PPI::Token::Structure         ';'
#       PPI::Statement
#         PPI::Token::Symbol    '$XV'
#         PPI::Token::Whitespace        ' '
#         PPI::Token::Word      'Xs'
#         PPI::Token::Magic     '%-'
#         PPI::Token::Word      't'
#         PPI::Token::Whitespace        '\t'
#         PPI::Token::Word      'g'
#         PPI::Token::Operator          '*'
#         PPI::Token::Quote::Single     ''\n^Vs8g?|\}>,1wb[~f|bb{-<)gs:ft}=wy9<X''
#         PPI::Token::Word      'r'
#         PPI::Token::Operator          ','
#         PPI::Token::QuoteLike::Backtick       '`,\t,"\n}>:c0bb~sq}\f\n|{^_cmcm\+<0,){=:s?*%s`'
#         PPI::Token::Operator          '-'
#         PPI::Token::Number    '0'
#         PPI::Token::Word      'mr'
#         PPI::Token::Operator          '&&'
#         PPI::Token::Word      'V'
#         PPI::Structure::Constructor   [ ... ???
#           PPI::Statement
#             PPI::Token::Word          'W'
#             PPI::Token::QuoteLike::Readline   '<>'
#             PPI::Token::Word          'r'
#             PPI::Token::Operator      '|'
#             PPI::Token::QuoteLike::Backtick   '`9<r%+-9(\t!\:r`'
#             PPI::Token::Operator      '.'
#   PPI::Statement::UnmatchedBrace
#     PPI::Token::Structure     ')'
#   PPI::Statement
#     PPI::Token::Word          'VW'
#     PPI::Token::Operator      '?'
#     PPI::Token::Word          'z'
#     PPI::Token::Operator      '^'
#     PPI::Token::Word          'c'
#     PPI::Token::HereDoc       '<<~"\t'1V`%__;@9)^gc{s@ q#"'
#     PPI::Token::Word          't'
#     PPI::Structure::Block     { ... ???
#       PPI::Token::Whitespace          ' '
#       PPI::Statement
#         PPI::Token::Regexp::Substitute        's<@\n'
# Looks like you failed 4 tests of 1067.
```

**Comment by wchristian** [comment] 2019-05-16 09:26
Thanks for bringing it up. The cause was PPI::Test::Run not being sufficiently OS-agnostic, which is fixed in https://metacpan.org/release/MITHALDU/PPI-1.267

**Closed by wchristian** 2019-05-16 09:26 UTC
