### ISSUE TITLE
':' interpreted as a label identifier

### ISSUE THREAD

**Issue by drforr** [adamkennedy/PPI#178] opened 2015-08-24 18:10 UTC
isa() ? shift : die;

ppidump reports this parse as:

```
                    PPI::Document
                      PPI::Statement
[    1,   1,   1 ]     PPI::Token::Word         'isa'
                        PPI::Structure::List    ( ... )
[    1,   7,   7 ]     PPI::Token::Operator     '?'
[    1,   9,   9 ]     PPI::Token::Label        'shift :'
[    1,  17,  17 ]     PPI::Token::Word         'die'
[    1,  20,  20 ]     PPI::Token::Structure    ';'
```

**Comment by moregan** [comment] 2017-05-17 17:25
This is a duplicate of issue #62

**Closed by moregan** 2017-05-17 17:25 UTC
